<?php

// File generated from our OpenAPI spec

namespace Bkash\Util;

class ObjectTypes
{
    /**
     * @var array Mapping from object types to resource classes
     */
    const mapping = [
        \Bkash\Account::OBJECT_NAME => \Bkash\Account::class,
        \Bkash\AccountLink::OBJECT_NAME => \Bkash\AccountLink::class,
        \Bkash\ApplePayDomain::OBJECT_NAME => \Bkash\ApplePayDomain::class,
        \Bkash\ApplicationFee::OBJECT_NAME => \Bkash\ApplicationFee::class,
        \Bkash\ApplicationFeeRefund::OBJECT_NAME => \Bkash\ApplicationFeeRefund::class,
        \Bkash\Apps\Secret::OBJECT_NAME => \Bkash\Apps\Secret::class,
        \Bkash\Balance::OBJECT_NAME => \Bkash\Balance::class,
        \Bkash\BalanceTransaction::OBJECT_NAME => \Bkash\BalanceTransaction::class,
        \Bkash\BankAccount::OBJECT_NAME => \Bkash\BankAccount::class,
        \Bkash\BillingPortal\Configuration::OBJECT_NAME => \Bkash\BillingPortal\Configuration::class,
        \Bkash\BillingPortal\Session::OBJECT_NAME => \Bkash\BillingPortal\Session::class,
        \Bkash\Capability::OBJECT_NAME => \Bkash\Capability::class,
        \Bkash\Card::OBJECT_NAME => \Bkash\Card::class,
        \Bkash\CashBalance::OBJECT_NAME => \Bkash\CashBalance::class,
        \Bkash\Charge::OBJECT_NAME => \Bkash\Charge::class,
        \Bkash\Checkout\Session::OBJECT_NAME => \Bkash\Checkout\Session::class,
        \Bkash\Collection::OBJECT_NAME => \Bkash\Collection::class,
        \Bkash\CountrySpec::OBJECT_NAME => \Bkash\CountrySpec::class,
        \Bkash\Coupon::OBJECT_NAME => \Bkash\Coupon::class,
        \Bkash\CreditNote::OBJECT_NAME => \Bkash\CreditNote::class,
        \Bkash\CreditNoteLineItem::OBJECT_NAME => \Bkash\CreditNoteLineItem::class,
        \Bkash\Customer::OBJECT_NAME => \Bkash\Customer::class,
        \Bkash\CustomerBalanceTransaction::OBJECT_NAME => \Bkash\CustomerBalanceTransaction::class,
        \Bkash\CustomerCashBalanceTransaction::OBJECT_NAME => \Bkash\CustomerCashBalanceTransaction::class,
        \Bkash\Discount::OBJECT_NAME => \Bkash\Discount::class,
        \Bkash\Dispute::OBJECT_NAME => \Bkash\Dispute::class,
        \Bkash\EphemeralKey::OBJECT_NAME => \Bkash\EphemeralKey::class,
        \Bkash\Event::OBJECT_NAME => \Bkash\Event::class,
        \Bkash\ExchangeRate::OBJECT_NAME => \Bkash\ExchangeRate::class,
        \Bkash\File::OBJECT_NAME => \Bkash\File::class,
        \Bkash\File::OBJECT_NAME_ALT => \Bkash\File::class,
        \Bkash\FileLink::OBJECT_NAME => \Bkash\FileLink::class,
        \Bkash\FinancialConnections\Account::OBJECT_NAME => \Bkash\FinancialConnections\Account::class,
        \Bkash\FinancialConnections\AccountOwner::OBJECT_NAME => \Bkash\FinancialConnections\AccountOwner::class,
        \Bkash\FinancialConnections\AccountOwnership::OBJECT_NAME => \Bkash\FinancialConnections\AccountOwnership::class,
        \Bkash\FinancialConnections\Session::OBJECT_NAME => \Bkash\FinancialConnections\Session::class,
        \Bkash\FundingInstructions::OBJECT_NAME => \Bkash\FundingInstructions::class,
        \Bkash\Identity\VerificationReport::OBJECT_NAME => \Bkash\Identity\VerificationReport::class,
        \Bkash\Identity\VerificationSession::OBJECT_NAME => \Bkash\Identity\VerificationSession::class,
        \Bkash\Invoice::OBJECT_NAME => \Bkash\Invoice::class,
        \Bkash\InvoiceItem::OBJECT_NAME => \Bkash\InvoiceItem::class,
        \Bkash\InvoiceLineItem::OBJECT_NAME => \Bkash\InvoiceLineItem::class,
        \Bkash\Issuing\Authorization::OBJECT_NAME => \Bkash\Issuing\Authorization::class,
        \Bkash\Issuing\Card::OBJECT_NAME => \Bkash\Issuing\Card::class,
        \Bkash\Issuing\CardDetails::OBJECT_NAME => \Bkash\Issuing\CardDetails::class,
        \Bkash\Issuing\Cardholder::OBJECT_NAME => \Bkash\Issuing\Cardholder::class,
        \Bkash\Issuing\Dispute::OBJECT_NAME => \Bkash\Issuing\Dispute::class,
        \Bkash\Issuing\Transaction::OBJECT_NAME => \Bkash\Issuing\Transaction::class,
        \Bkash\LineItem::OBJECT_NAME => \Bkash\LineItem::class,
        \Bkash\LoginLink::OBJECT_NAME => \Bkash\LoginLink::class,
        \Bkash\Mandate::OBJECT_NAME => \Bkash\Mandate::class,
        \Bkash\Order::OBJECT_NAME => \Bkash\Order::class,
        \Bkash\PaymentIntent::OBJECT_NAME => \Bkash\PaymentIntent::class,
        \Bkash\PaymentLink::OBJECT_NAME => \Bkash\PaymentLink::class,
        \Bkash\PaymentMethod::OBJECT_NAME => \Bkash\PaymentMethod::class,
        \Bkash\Payout::OBJECT_NAME => \Bkash\Payout::class,
        \Bkash\Person::OBJECT_NAME => \Bkash\Person::class,
        \Bkash\Plan::OBJECT_NAME => \Bkash\Plan::class,
        \Bkash\Price::OBJECT_NAME => \Bkash\Price::class,
        \Bkash\Product::OBJECT_NAME => \Bkash\Product::class,
        \Bkash\PromotionCode::OBJECT_NAME => \Bkash\PromotionCode::class,
        \Bkash\Quote::OBJECT_NAME => \Bkash\Quote::class,
        \Bkash\Radar\EarlyFraudWarning::OBJECT_NAME => \Bkash\Radar\EarlyFraudWarning::class,
        \Bkash\Radar\ValueList::OBJECT_NAME => \Bkash\Radar\ValueList::class,
        \Bkash\Radar\ValueListItem::OBJECT_NAME => \Bkash\Radar\ValueListItem::class,
        \Bkash\Refund::OBJECT_NAME => \Bkash\Refund::class,
        \Bkash\Reporting\ReportRun::OBJECT_NAME => \Bkash\Reporting\ReportRun::class,
        \Bkash\Reporting\ReportType::OBJECT_NAME => \Bkash\Reporting\ReportType::class,
        \Bkash\Review::OBJECT_NAME => \Bkash\Review::class,
        \Bkash\SearchResult::OBJECT_NAME => \Bkash\SearchResult::class,
        \Bkash\SetupAttempt::OBJECT_NAME => \Bkash\SetupAttempt::class,
        \Bkash\SetupIntent::OBJECT_NAME => \Bkash\SetupIntent::class,
        \Bkash\ShippingRate::OBJECT_NAME => \Bkash\ShippingRate::class,
        \Bkash\Sigma\ScheduledQueryRun::OBJECT_NAME => \Bkash\Sigma\ScheduledQueryRun::class,
        \Bkash\SKU::OBJECT_NAME => \Bkash\SKU::class,
        \Bkash\Source::OBJECT_NAME => \Bkash\Source::class,
        \Bkash\SourceTransaction::OBJECT_NAME => \Bkash\SourceTransaction::class,
        \Bkash\Subscription::OBJECT_NAME => \Bkash\Subscription::class,
        \Bkash\SubscriptionItem::OBJECT_NAME => \Bkash\SubscriptionItem::class,
        \Bkash\SubscriptionSchedule::OBJECT_NAME => \Bkash\SubscriptionSchedule::class,
        \Bkash\TaxCode::OBJECT_NAME => \Bkash\TaxCode::class,
        \Bkash\TaxId::OBJECT_NAME => \Bkash\TaxId::class,
        \Bkash\TaxRate::OBJECT_NAME => \Bkash\TaxRate::class,
        \Bkash\Terminal\Configuration::OBJECT_NAME => \Bkash\Terminal\Configuration::class,
        \Bkash\Terminal\ConnectionToken::OBJECT_NAME => \Bkash\Terminal\ConnectionToken::class,
        \Bkash\Terminal\Location::OBJECT_NAME => \Bkash\Terminal\Location::class,
        \Bkash\Terminal\Reader::OBJECT_NAME => \Bkash\Terminal\Reader::class,
        \Bkash\TestHelpers\TestClock::OBJECT_NAME => \Bkash\TestHelpers\TestClock::class,
        \Bkash\Token::OBJECT_NAME => \Bkash\Token::class,
        \Bkash\Topup::OBJECT_NAME => \Bkash\Topup::class,
        \Bkash\Transfer::OBJECT_NAME => \Bkash\Transfer::class,
        \Bkash\TransferReversal::OBJECT_NAME => \Bkash\TransferReversal::class,
        \Bkash\Treasury\CreditReversal::OBJECT_NAME => \Bkash\Treasury\CreditReversal::class,
        \Bkash\Treasury\DebitReversal::OBJECT_NAME => \Bkash\Treasury\DebitReversal::class,
        \Bkash\Treasury\FinancialAccount::OBJECT_NAME => \Bkash\Treasury\FinancialAccount::class,
        \Bkash\Treasury\FinancialAccountFeatures::OBJECT_NAME => \Bkash\Treasury\FinancialAccountFeatures::class,
        \Bkash\Treasury\InboundTransfer::OBJECT_NAME => \Bkash\Treasury\InboundTransfer::class,
        \Bkash\Treasury\OutboundPayment::OBJECT_NAME => \Bkash\Treasury\OutboundPayment::class,
        \Bkash\Treasury\OutboundTransfer::OBJECT_NAME => \Bkash\Treasury\OutboundTransfer::class,
        \Bkash\Treasury\ReceivedCredit::OBJECT_NAME => \Bkash\Treasury\ReceivedCredit::class,
        \Bkash\Treasury\ReceivedDebit::OBJECT_NAME => \Bkash\Treasury\ReceivedDebit::class,
        \Bkash\Treasury\Transaction::OBJECT_NAME => \Bkash\Treasury\Transaction::class,
        \Bkash\Treasury\TransactionEntry::OBJECT_NAME => \Bkash\Treasury\TransactionEntry::class,
        \Bkash\UsageRecord::OBJECT_NAME => \Bkash\UsageRecord::class,
        \Bkash\UsageRecordSummary::OBJECT_NAME => \Bkash\UsageRecordSummary::class,
        \Bkash\WebhookEndpoint::OBJECT_NAME => \Bkash\WebhookEndpoint::class,
    ];
}
